import React from "react";
import { useTheme } from "next-themes";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { ReactNode, useId, useState, useEffect } from "react";
import Select, { StylesConfig } from "react-select";
import {
  auth,
  createUserWithEmailAndPassword,
  signInWithEmailAndPassword,
} from "../firebase";
import { onAuthStateChanged, signOut } from "firebase/auth";
import AlertBar from "./AlertBar";
interface Bet {
  match: string; // Ou un autre type selon votre logique
  // autres propriétés du bet
}
interface Option {
  value: string;
  label: string;
}
const options = [{ value: "FR", label: "FR" }];
const langOptions = [{ value: "Français", label: "Francais" }];
const decimalOptions = [
  { value: "Decimal", label: "Decimal" },
  { value: "Odds", label: "Odds" },
];
type Props = {
  children: ReactNode;
  // Other props
};
export default function Layout({ children }: Props) {
  const [selectedOdds, setSelectedOdds] = useState([]);
  const { theme, setTheme } = useTheme();
  const [selectedOption, setSelectedOption] = useState<Option | null | unknown>(
    options[0]
  );
  const [selectedLangOption, setSelectedLangOption] = useState<
    Option | null | unknown
  >(langOptions[0]);
  const [selectedDacimalOption, setSelectedDacimalOption] = useState<
    Option | null | unknown
  >(decimalOptions[0]);
  const [openMenu, setOpenMenu] = useState(false);
  const [openMenu2, setOpenMenu2] = useState(false);
  const inactiveTheme = theme === "light" ? "dark" : "light";
  const { pathname } = useRouter();

  const customStyles: StylesConfig = {
    control: (provided, state) => ({
      ...provided,
      backgroundColor: theme !== "dark" ? "#1F493F" : "#D5DDEC",
      borderColor: "#1F493F",
      border: state.isFocused ? "0" : "0",
    }),
    option: (provided, state) => ({
      ...provided,
      color: state.isSelected ? "#ffffff" : "#000",
      backgroundColor: state.isSelected ? "#1F493F" : "#ffffff",
    }),
    singleValue: (base) => ({
      ...base,
      color: theme !== "dark" ? "#fff" : "#000",
      border: "none",
    }),
  };

  // const handleRegister = async (e) => {
  //   e.preventDefault();
  //   try {
  //     const userCredential = await createUserWithEmailAndPassword(
  //       auth,
  //       email,
  //       password
  //     );
  //     console.log("Utilisateur créé :", userCredential.user);
  //     alert("Compte créé avec succès !");
  //   } catch (error) {
  //     setError(error.message);
  //   }
  // };

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault();
    try {
      const userCredential = await createUserWithEmailAndPassword(
        auth,
        email,
        password
      );
      console.log("Utilisateur créé :", userCredential.user);
      alert("Compte créé avec succès !");
    } catch (error) {
      if (error instanceof Error) {
        setError(error.message);
      } else {
        setError("Une erreur inconnue est survenue.");
      }
    }
  };


  // Fonction pour ajouter une cote sélectionnée
  const handleSelectOdds = (bet) => {
    // @ts-ignore
    setSelectedOdds((prevOdds) => {
      // Vérifie si une cote sur le même match existe déjà
      // @ts-ignore
      const alreadyExists = prevOdds.some((odds) => odds.match === bet.match);
      if (alreadyExists) {
        // @ts-ignore
        return prevOdds.map((odds) => (odds.match === bet.match ? bet : odds));
      }
      return [...prevOdds, bet];
    });
  };

 

  useEffect(() => {
    // Surveiller l'état de connexion de l'utilisateur
    const unsubscribe = onAuthStateChanged(auth, (currentUser) => {
      // @ts-ignore
      setUser(currentUser);
    });

    return () => unsubscribe(); // Nettoyage de l'écouteur
  }, []);

  const handleLogout = async () => {
    await signOut(auth);
    console.log("Utilisateur déconnecté");
  };

  const handleLogin = async (e) => {
    e.preventDefault();

    try {
      await signInWithEmailAndPassword(auth, email, password);
      alert("Connexion réussie !");
    } catch (error) {
      setError("Échec de la connexion. Vérifiez vos informations.");
      // @ts-ignore
      console.error("Erreur de connexion :", error.message);
    }
  };

  const [user, setUser] = useState(null);
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [name, setName] = useState("");
  const [ddn, setDdn] = useState("");
  const [error, setError] = useState("");

  return (
    <>
      <Head>
        <title> Ybet - Décide et Gagne </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <header className="header-section header-hidden">
          <div className="header-wrapper">
            <div className="menu-logo-adjust d-flex align-items-center">
              <div className="logo-menu me-5">
                <Link href="/" className="logo">
                  <img src="/img/logo/logo.png" alt="logo" />
                </Link>
                <Link href="/" className="dark-logo">
                  <img src="/img/logo/dark-logo.png" alt="logo" />
                </Link>
              </div>
              <div
                className={`header-bar ${openMenu && "active act"}`}
                onClick={() => setOpenMenu(!openMenu)}
              >
                <span></span>
                <span></span>
                <span></span>
              </div>
              <ul className={`main-menu ${openMenu && "active act"}`}>
                <li>
                  <Link className={pathname == "/" ? "text-base" : ""} href="/">
                    Accueil
                  </Link>
                </li>
                <li>
                  <Link
                    className={pathname == "/live" ? "text-base" : ""}
                    href="/live"
                  >
                    Live
                  </Link>
                </li>
                <li>
                  <Link
                    className={pathname == "/football" ? "text-base" : ""}
                    href="/football"
                  >
                    Sports
                  </Link>
                </li>

                {/* <li>
                  <Link
                    className={pathname == "/profile" ? "text-base" : ""}
                    href="/profile"
                  >
                    Promotions
                  </Link>
                </li> */}
                {/* <li>
                  <Link
                    className={pathname == "/efootball" ? "text-base" : ""}
                    href="/efootball"
                  >
                    eSports
                  </Link>
                </li> */}
                {/* <li>
                  <Link
                    href="#0"
                    data-bs-toggle="modal"
                    data-bs-target="#exampleModal2"
                  >
                    Quick Bets
                  </Link>
                </li> */}
                <li className="menu--btn">
                  <Link
                    href="#0"
                    className="btn--two"
                    data-bs-toggle="modal"
                    data-bs-target="#exampleModal"
                  >
                    <span>Log In</span>
                  </Link>
                </li>
                <li className="menu--btn">
                  <Link
                    href="#0"
                    className="cmn--btn"
                    data-bs-toggle="modal"
                    data-bs-target="#exampleModal2"
                  >
                    <span>Sign Up</span>
                  </Link>
                </li>
              </ul>
            </div>
            <div className="right-menu-reature">
              <div className="language">
                <div className="d-flex gap-2 align-items-center">
                  {/* <span className="current">En</span>
                  <ul className="list">
                    <li data-value="1" className="option selected focus">En</li>
                    <li data-value="2" className="option">Bn</li>
                    <li data-value="3" className="option">Us</li>
                  </ul> */}

                  <div className="glo">
                    <i className="fas fa-globe"></i>
                  </div>
                  <Select
                    instanceId={useId()}
                    defaultValue={selectedOption}
                    onChange={setSelectedOption}
                    options={options}
                    components={{
                      IndicatorSeparator: () => null,
                    }}
                    styles={customStyles}
                  />
                </div>
              </div>
              <div
                className="mode--toggle"
                onClick={() => setTheme(inactiveTheme)}
              >
                <img
                  src={`/img/${theme === "dark" ? "moon" : "sun"}.png`}
                  alt=""
                />
              </div>

              <div className="signup-area">
                {user ? (
                  // Si l'utilisateur est connecté
                  <>
                    <Link href="/profile" className="cmn--btn">
                      <span>Profil</span>
                    </Link>
                    <button onClick={handleLogout} className="btn--two">
                      <span>Déconnexion</span>
                    </button>
                  </>
                ) : (
                  // Si l'utilisateur n'est pas connecté
                  <>
                    <Link
                      href="#0"
                      className="btn--two"
                      data-bs-toggle="modal"
                      data-bs-target="#exampleModal"
                    >
                      <span>Connexion</span>
                    </Link>
                    <Link
                      href="#0"
                      className="cmn--btn"
                      data-bs-toggle="modal"
                      data-bs-target="#exampleModal2"
                    >
                      <span>Inscription</span>
                    </Link>
                  </>
                )}
              </div>
            </div>
          </div>
        </header>
        {/* <!--==== Header top End  ====== --> */}

        {/* <!--Main Body Section Here--> */}
        {/* <!--Main Body Section Here--> */}
        <div className="main-body">
          {/* <!--Left Box Menu--> */}
          <div className="left-site-menu">
            <div className="left-box">
              <header className="header">
                <nav className={`menu ${openMenu2 && "active act"}`}>
                  <ul className="main-list-menu">
                    <li>
                      <ul className="menu-promot menu-promot-first">
                        <li>
                          <form action="#">
                            <input
                              type="text"
                              placeholder="Rechercher un sport..."
                            />
                            <span className="icon">
                              <i className="fas fa-magnifying-glass"></i>
                            </span>
                          </form>
                        </li>
                        <li>
                          <Link
                            href="/"
                            className={`${pathname == "/" && "active"}`}
                          >
                            <div className="icon">
                              <i className="icon-home"></i>
                            </div>
                            <span>Accueil</span>
                          </Link>
                          <Link
                            href="live"
                            className={`main-list-menu-live ${
                              pathname == "/live" && "active"
                            }`}
                          >
                            <div className="icon">
                              <i className="icon-live"></i>
                            </div>
                            <span>Live</span>
                            <span className="live-watch">10</span>
                          </Link>
                          <Link
                            href="favorites"
                            className={`${
                              pathname == "/favorites" && "active"
                            }`}
                          >
                            <div className="icon">
                              <i className="fas fa-star"></i>
                            </div>
                            <span>Favori</span>
                          </Link>
                        </li>
                      </ul>
                    </li>
                    <li>
                      <ul className="menu-promot menu-promot-bottom">
                        <li className="pro">Jeux</li>
                        <li className="original-sub">
                          <div className="dd">
                            <div
                              className={`dd-a d-flex align-items-center justify-content-between`}
                            >
                              <div className={`cont d-flex align-items-center`}>
                                <div className="icon">
                                  <i className="icon-football"></i>
                                </div>
                                <span>Football</span>
                              </div>
                              <span>
                                <i className="fas fa-angle-down"></i>
                              </span>
                            </div>
                            <input type="checkbox" />
                            <div className="dd-c">
                              <ul>
                                <li>
                                  <Link href="football">
                                    <div className="icon">
                                      <i className="icon-football"></i>
                                    </div>
                                    <span>Football</span>
                                  </Link>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </li>

                        <li>
                          <Link
                            href="basketball"
                            className={`${
                              pathname == "/basketball" && "active"
                            }`}
                          >
                            <div className="icon">
                              <i className="icon-basketball"></i>
                            </div>
                            <span>Basketball</span>
                          </Link>
                        </li>

                        <li>
                          <Link
                            href="tennis"
                            className={`${pathname == "/tennis" && "active"}`}
                          >
                            <div className="icon">
                              <i className="icon-tennis"></i>
                            </div>
                            <span>Tennis</span>
                          </Link>
                        </li>

                        <li>
                          <Link
                            href="volleyball"
                            className={`${
                              pathname == "/volleyball" && "active"
                            }`}
                          >
                            <div className="icon">
                              <i className="icon-volleyball"></i>
                            </div>
                            <span>Volleyball</span>
                          </Link>
                        </li>
                        <li>
                          <Link
                            href="baseball"
                            className={`${pathname == "/baseball" && "active"}`}
                          >
                            <div className="icon">
                              <i className="icon-baseball"></i>
                            </div>
                            <span>Baseball</span>
                          </Link>
                        </li>
                        <li>
                          <Link
                            href="rugby"
                            className={`${pathname == "/rugby" && "active"}`}
                          >
                            <div className="icon">
                              <i className="icon-rugby"></i>
                            </div>
                            <span>Rugby</span>
                          </Link>
                        </li>
                        <li>
                          <Link
                            href="mma"
                            className={`${pathname == "/mma" && "active"}`}
                          >
                            <div className="icon">
                              <i className="icon-mma"></i>
                            </div>
                            <span>MMA</span>
                          </Link>
                        </li>
                        <li>
                          <Link
                            href="americanfootball"
                            className={`${
                              pathname == "/americanfootball" && "active"
                            }`}
                          >
                            <div className="icon">
                              <i className="icon-americanball"></i>
                            </div>
                            <span>Football Americain</span>
                          </Link>
                        </li>
                        <li>
                          <Link
                            href="handball"
                            className={`${pathname == "/handball" && "active"}`}
                          >
                            <div className="icon">
                              <i className="icon-handball"></i>
                            </div>
                            <span>Handball</span>
                          </Link>
                        </li>

                        <li>
                          <Link
                            href="boxing"
                            className={`${pathname == "/boxing" && "active"}`}
                          >
                            <div className="icon">
                              <i className="icon-boxing"></i>
                            </div>
                            <span>Boxe</span>
                          </Link>
                        </li>
                      </ul>
                    </li>
                  </ul>
                  <div
                    className={`hamburger ${openMenu2 && "active act"}`}
                    onClick={() => setOpenMenu2(!openMenu2)}
                  >
                    <span></span>
                  </div>
                  <div
                    className={`hamb ${openMenu2 && "active act"}`}
                    onClick={() => setOpenMenu2(!openMenu2)}
                  >
                    <span></span>
                  </div>
                  <div className={`dimmer ${openMenu2 && "active act"}`}></div>
                </nav>
              </header>
            </div>
          </div>
          {/* <!--Left Box Menu--> */}

          {/* <!--Middle Body--> */}
          <div className="body-middle">
            {children}
            {/* // <!--Footer Section--> */}
            <footer className="footer-section">
              <div className="container">
                <div className="footer-wrapper">
                  <p>
                    Copyright {new Date().getFullYear().toString()}{" "}
                    <Link href="#0" className="text-base">
                      YBET
                    </Link>{" "}
                    Tout droits Reserved.
                  </p>
                </div>
              </div>
            </footer>
            {/* // <!--Footer Section--> */}
            <Link
              href="#0"
              className="click-btn"
              data-bs-toggle="modal"
              data-bs-target="#exampleModal3"
            >
              <i className="icon-basketball"></i>
            </Link>
          </div>
          {/* // <!--Middle Body--> */}

          {/* // <!--Right Box Chat--> */}
          <div className="right-site-menu">
            <div className="right-box">
              <div className="right-wrapper-area">
                <div className="blance-items">
                  <div className="left-blance">
                    <span>
                      <img src="/img/header/right-icon/wallet.svg" alt="icon" />
                    </span>
                    <span className="text-blabce">Votre Solde</span>
                  </div>
                  <span className="blance">0 FCFA</span>
                </div>
                <div className="betslip-wrapper">
                  <Link href="#0" className="left-betslip">
                    <span className="bed2">
                      <img src="/img/header/right-icon/bed2.png" alt="icon" />
                    </span>
                    <span className="bed1">
                      <img src="/img/header/right-icon/bed.svg" alt="icon" />
                    </span>
                    <span className="text-bets">Fiche de pari</span>
                  </Link>
                  <Link href="#0" className="left-betslip">
                    <span>
                      <img src="/img/header/right-icon/bets.svg" alt="icon" />
                    </span>
                    <span className="text-bets">Mes Paris</span>
                  </Link>
                </div>
                <div className="combo-box">
                  <ul className="nav">
                    <li className="nav-item">
                      <Link
                        className="nav-link link-secondary"
                        id="combo-tab"
                        data-bs-toggle="tab"
                        data-bs-target="#coombo"
                        href="#"
                      >
                        <span>Pari Unique</span>
                      </Link>
                    </li>
                    <li className="nav-item">
                      <Link
                        className="nav-link link-secondary active"
                        id="bets-tab"
                        data-bs-toggle="tab"
                        data-bs-target="#bbets"
                        href="#"
                      >
                        <span>Combiné</span>
                      </Link>
                    </li>
                  </ul>
                  <div className="tab-content" id="tabContentboxes">
                    <div className="tab-pane fade" id="coombo" role="tabpanel">
                      <div className="combo-wrapper">
                        <div className="combo-wrapper">
                          <div className="close-box">
                            <div className="close-items">
                              <div className="close-head">
                                <span>Latvia vs Moldova</span>
                                <span className="close">
                                  <i className="fas fa-xmark"></i>
                                </span>
                              </div>
                              <div className="match-fixing">
                                <div className="match-items">
                                  <div className="match-items-left">
                                    <div className="icon">
                                      <img
                                        src="/img/header/right-icon/footaball.svg"
                                        alt="icon"
                                      />
                                    </div>
                                    <div className="cont">
                                      <span>Moldova</span>
                                      <span className="winner">
                                        Match Winner
                                      </span>
                                    </div>
                                  </div>
                                  <div className="match-items-right">
                                    <div className="icon">
                                      <img
                                        src="/img/header/right-icon/uptodwon.svg"
                                        alt="icon"
                                      />
                                    </div>
                                    <span>5.20</span>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="combo-switch">
                            <span>Accepter tous les changements de cotes</span>
                            <label className="switch-com">
                              <input
                                type="checkbox"
                                className="checkbox"
                                hidden
                              />
                              <span className="checkbox-label">
                                <span className="ball"></span>
                              </span>
                            </label>
                          </div>
                          <div className="ammount-items">
                            <form action="#">
                              <input type="number" placeholder="Bet Amount" />
                              <button type="submit">Max</button>
                            </form>
                          </div>
                          <div className="possible-win">
                            <span>Victoire possible</span>
                            <span className="amount">$300</span>
                          </div>
                          <div className="combo-footer">
                            <Link href="#0" className="cmn--btn">
                              <span> Placer un pari </span>
                            </Link>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      className="tab-pane fade show active"
                      id="bbets"
                      role="tabpanel"
                    >
                      <div className="combo-wrapper">
                        <div className="close-box">
                          <div className="close-items">
                            <div className="close-head">
                              <span>Scotland vs Ukraine</span>
                              <span className="close">
                                <i className="fas fa-xmark"></i>
                              </span>
                            </div>
                            <div className="match-fixing">
                              <div className="match-items">
                                <div className="match-items-left">
                                  <div className="icon">
                                    <img
                                      src="/img/header/right-icon/footaball.svg"
                                      alt="icon"
                                    />
                                  </div>
                                  <div className="cont">
                                    <span>Scotland</span>
                                    <span className="winner">Match Winner</span>
                                  </div>
                                </div>
                                <div className="match-items-right">
                                  <div className="icon">
                                    <img
                                      src="/img/header/right-icon/uptodwon.svg"
                                      alt="icon"
                                    />
                                  </div>
                                  <span>3.20</span>
                                </div>
                              </div>
                              <div className="match-items">
                                <div className="match-items-left">
                                  <div className="icon">
                                    <img
                                      src="/img/header/right-icon/footaball.svg"
                                      alt="icon"
                                    />
                                  </div>
                                  <div className="cont">
                                    <span>Draw</span>
                                    <span className="winner">Match Winner</span>
                                  </div>
                                </div>
                                <div className="match-items-right">
                                  <div className="icon">
                                    <img
                                      src="/img/header/right-icon/uptodwon.svg"
                                      alt="icon"
                                    />
                                  </div>
                                  <span>4.60</span>
                                </div>
                              </div>
                              <p>
                                Add 2 more outcome(s) with odds greater than 1.4
                                to get x1.08
                              </p>
                              <div className="match-items match-progress">
                                <div className="match-items-left">
                                  <div className="prabox-wrap">
                                    <div className="terminal-bar">
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                      <span></span>
                                    </div>
                                    <div className="bar-count">
                                      <p>x1.08</p>
                                      <p>x1,15</p>
                                      <p>x1.20</p>
                                      <p>x1.50</p>
                                    </div>
                                  </div>
                                </div>
                                <div className="match-items-right">
                                  <div className="icon">
                                    <img
                                      src="/img/header/right-icon/uptodwon.svg"
                                      alt="icon"
                                    />
                                  </div>
                                  <span>1.00</span>
                                </div>
                              </div>
                              <div className="match-items match-odds">
                                <div className="match-items-left">
                                  <div className="cont">
                                    <span>Total des cotes</span>
                                  </div>
                                </div>
                                <div className="match-items-right">
                                  <div className="icon">
                                    <img
                                      src="/img/header/right-icon/uptodwon.svg"
                                      alt="icon"
                                    />
                                  </div>
                                  <span>12.19</span>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="combo-switch">
                          <span>Accepter tous les changements de cotes</span>
                          <label className="switch-com">
                            <input
                              type="checkbox"
                              className="checkbox"
                              hidden
                            />
                            <span className="checkbox-label">
                              <span className="ball"></span>
                            </span>
                          </label>
                        </div>
                        <div className="ammount-items">
                          <form action="#">
                            <input
                              type="number"
                              placeholder="Montant du pari"
                            />
                            <button type="submit">Max</button>
                          </form>
                        </div>
                        <div className="possible-win">
                          {/* <span>Possible win</span>
                          <span className="amount">$300</span> */}
                        </div>
                        <div className="combo-footer">
                          <Link href="#0" className="cmn--btn">
                            <span> Placer un pari</span>
                          </Link>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* <button
                          className="accordion-button collapsed"
                          type="button"
                          data-bs-toggle="collapse"
                          data-bs-target="#collapseThree"
                          aria-expanded="false"
                          aria-controls="collapseThree"
                        >
                          <span className="icon">
                            <i className="fa-sharp fa-solid fa-gear"></i>
                          </span>
                          <span>Paramettre</span>
                        </button> */}
                {/* <div
                          id="collapseThree"
                          className="accordion-collapse collapse"
                          data-bs-parent="#accordionExample"
                        >
                          <div className="accordion-body">
                            <div className="select-wrap">
                              <div className="select-one">
                                <Select
                                  instanceId={useId()}
                                  defaultValue={selectedLangOption}
                                  onChange={setSelectedLangOption}
                                  options={langOptions}
                                  components={{
                                    IndicatorSeparator: () => null,
                                  }}
                                  styles={customStyles}
                                />
                              </div>
                              <div className="select-two">
                                <Select
                                  instanceId={useId()}
                                  defaultValue={selectedDacimalOption}
                                  onChange={setSelectedDacimalOption}
                                  options={decimalOptions}
                                  components={{
                                    IndicatorSeparator: () => null,
                                  }}
                                  styles={customStyles}
                                />
                              </div>
                            </div>
                            <Link href="#0" className="condition-box">
                              Terms & Conditions
                            </Link>
                          </div>
                        </div> */}
                {/* </div>
                    </div>
                  </div> */}
                {/* </div> */}
              </div>
              {/* <div className="popular-bets">
                <div className="head">
                  <h6>Paris Populaire</h6>
                </div>
                <ul className="popoular-body">
                  <li className="popular-items">
                    <label className="popular-itmes-left">
                      <input
                        className="form-check-input"
                        type="checkbox"
                        id="flexCheckDefault1"
                      />
                      <span className="icon">
                        <i className="icon-football"></i>
                      </span>
                      <span className="cont">
                        <span className="text1">1x2</span>
                        <span className="text2">Prance</span>
                        <span className="text3">France - Austria</span>
                      </span>
                    </label>
                    <div className="popular-itmes-right">
                      <span>2.37</span>
                    </div>
                  </li>
                  <li className="popular-items">
                    <label className="popular-itmes-left">
                      <input
                        className="form-check-input"
                        type="checkbox"
                        id="flexCheckDefault2"
                      />
                      <span className="icon">
                        <i className="icon-football"></i>
                      </span>
                      <span className="cont">
                        <span className="text1">1x2</span>
                        <span className="text2">Turkey</span>
                        <span className="text3">Turkey - Luxembourg</span>
                      </span>
                    </label>
                    <div className="popular-itmes-right">
                      <span>1.37</span>
                    </div>
                  </li>
                  <li className="popular-items">
                    <label className="popular-itmes-left">
                      <input
                        className="form-check-input"
                        type="checkbox"
                        id="flexCheckDefault3"
                      />
                      <span className="icon">
                        <i className="icon-football"></i>
                      </span>
                      <span className="cont">
                        <span className="text1">1x2</span>
                        <span className="text2">Alkmaar</span>
                        <span className="text3">Alkmaar - Apollon</span>
                      </span>
                    </label>
                    <div className="popular-itmes-right">
                      <span>3.47</span>
                    </div>
                  </li>
                </ul>
              </div> */}
            </div>
          </div>
          {/* // <!--Right Box Chat--> */}
        </div>
        {/* // <!--Main Body Section End--> */}
        {/* // <!--Main Body Section End--> */}

        {/* // <!-- Popup Section Start --> */}
        <div
          className="modal mylogin signup-popup fade"
          id="exampleModal"
          tabIndex={-1}
          aria-hidden="true"
        >
          <div className="modal-dialog modal-dialog-centered">
            <div className="modal-content">
              <div className="modal-header">
                <div className="head">
                  <h5>Connexion a votre Compte</h5>
                  <p>
                    Pas encore de compte ?{" "}
                    <Link href="#0" className="text-base">
                      Inscrivez-vous
                    </Link>
                  </p>
                </div>
              </div>
              <button
                type="button"
                className="btn-close cross-btn"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
              <div className="modal-body">
                <div className="register-from">
                  <form action="#0">
                    <div className="items">
                      <div className="form-input">
                        <label htmlFor="email3" className="form-label">
                          Email
                        </label>
                        <input
                          type="email"
                          id="email3"
                          placeholder="Votre Email"
                          name="email"
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                        />
                      </div>
                    </div>
                    <div className="items">
                      <div className="form-input">
                        <label htmlFor="password-field" className="form-label">
                          Password
                        </label>
                        <div className="form-group">
                          <input
                            id="password-field"
                            type="password"
                            className="form-control"
                            placeholder="Votre mot de passe"
                            name="password"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                          />
                          <span
                            id="#password-field"
                            className="fa fa-fw fa-eye field-icon toggle-password"
                          ></span>
                        </div>
                      </div>
                    </div>
                    <div className="items">
                      <div className="remember d-flex align-items-center justify-content-between">
                        <div className="form-check">
                          <label
                            className="form-check-label"
                            htmlFor="flexCheckDefault22"
                          >
                            <input
                              className="form-check-input"
                              type="checkbox"
                              id="flexCheckDefault22"
                            />
                            Restez Connecter
                          </label>
                        </div>
                        <Link href="#0" className="forget">
                          Mot de passe Oubliez ?
                        </Link>
                      </div>
                    </div>
                    {/* {error && <p style={{ color: "red" }}>{error}</p>} */}
                    <div className="items text-center">
                      <button
                        type="submit"
                        className="cmn--btn cd-popup-close repopup"
                        onClick={handleLogin}
                      >
                        <span>Commencer a jouer</span>
                      </button>
                    </div>

                    <div className="orbar">
                      <span>OU</span>
                    </div>
                    <ul className="log-social">
                      <li>
                        <Link href="#0">
                          <i className="fab fa-steam-symbol"></i>
                        </Link>
                      </li>
                      <li>
                        <Link href="#0">
                          <i className="fab fa-twitter"></i>
                        </Link>
                      </li>
                      <li>
                        <Link href="#0">
                          <i className="fab fa-linkedin-in"></i>
                        </Link>
                      </li>
                    </ul>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div
          className="modal mylogin fade"
          id="exampleModal2"
          tabIndex={-1}
          aria-hidden="true"
        >
          <div className="modal-dialog modal-dialog-centered">
            <div className="modal-content">
              <div className="modal-header">
                <div className="head">
                  <h5>Crée un Compte</h5>
                  <p>
                    Vous avez déja un Compte ?{" "}
                    <Link href="#0" className="text-base">
                      Connectez vous
                    </Link>
                  </p>
                </div>
              </div>
              <button
                type="button"
                className="btn-close cross-btn"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
              <div className="modal-body">
                <div className="register-from">
                  <form action="#0">
                    <div className="items">
                      <div className="form-input">
                        <label htmlFor="uname" className="form-label">
                          Nom et Prénoms
                        </label>
                        <input
                          type="text"
                          id="uname"
                          placeholder="Nom et Prénoms"
                          name="name"
                          value={name}
                          onChange={(e) => setName(e.target.value)}
                        />
                      </div>
                    </div>
                    <div className="items">
                      <div className="form-input">
                        <label htmlFor="email33" className="form-label">
                          Email
                        </label>
                        <input
                          type="email"
                          id="email33"
                          placeholder="Votre Email"
                          name="email"
                          value={email}
                          onChange={(e) => setEmail(e.target.value)}
                        />
                      </div>
                    </div>
                    <div className="items">
                      <div className="form-input">
                        <label htmlFor="date" className="form-label">
                          Date de naissance
                        </label>
                        <input
                          type="date"
                          id="date"
                          placeholder="Date de naissance"
                          name="ddn"
                          value={ddn}
                          onChange={(e) => setDdn(e.target.value)}
                        />
                      </div>
                    </div>
                    <div className="items">
                      <div className="form-input">
                        <label htmlFor="password-field" className="form-label">
                          Mot de passe
                        </label>
                        <div className="form-group">
                          <input
                            id="password-field2"
                            type="password"
                            className="form-control"
                            placeholder="Votre mot de passe"
                            name="password"
                            value={password}
                            onChange={(e) => setPassword(e.target.value)}
                          />
                          <span
                            id="#password-field2"
                            className="fa fa-fw fa-eye field-icon toggle-password2"
                          ></span>
                        </div>
                      </div>
                    </div>
                    <div className="items">
                      <div className="check-area">
                        <div className="form-check">
                          <input
                            className="form-check-input"
                            type="checkbox"
                            id="ones1"
                          />
                          <label className="form-check-label" htmlFor="ones1">
                            Je certifie que j'ai au moins 18 ans.
                          </label>
                        </div>
                        <div className="form-check">
                          <input
                            className="form-check-input"
                            type="checkbox"
                            id="ones2"
                          />
                          <label className="form-check-label" htmlFor="ones2">
                            J'accepte les{" "}
                            <Link href="#0" className="text-base">
                              Politique de confidentialité
                            </Link>
                          </label>
                        </div>
                        <div className="form-check">
                          <input
                            className="form-check-input"
                            type="checkbox"
                            id="ones3"
                          />
                          <label className="form-check-label" htmlFor="ones3">
                            Je veux recevoir{" "}
                            <Link href="#0" className="text-base">
                              nouvelles et offres
                            </Link>
                          </label>
                        </div>
                      </div>
                    </div>
                    <div className="items text-center">
                      <button
                        type="submit"
                        className="cmn--btn cd-popup-close repopup"
                        onClick={handleRegister}
                      >
                        <span>Commencer à jouer</span>
                      </button>
                    </div>
                    <div className="orbar">
                      <span>OU</span>
                    </div>
                    <ul className="log-social">
                      <li>
                        <Link href="#0">
                          <i className="fab fa-steam-symbol"></i>
                        </Link>
                      </li>
                      <li>
                        <Link href="#0">
                          <i className="fab fa-twitter"></i>
                        </Link>
                      </li>
                      <li>
                        <Link href="#0">
                          <i className="fab fa-linkedin-in"></i>
                        </Link>
                      </li>
                    </ul>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
        {/* // <!--menu modal--> */}
        <div
          className="modal right-menu-modal fade"
          id="exampleModal3"
          tabIndex={-1}
          aria-hidden="true"
        >
          <div className="modal-dialog modal-sm">
            <div className="modal-content">
              <button
                type="button"
                className="btn-close cross-btn"
                data-bs-dismiss="modal"
                aria-label="Close"
              ></button>
              <div className="modal-body">
                <div className="right-site-menu">
                  <div className="right-box">
                    <div className="right-wrapper-area">
                      <div className="blance-items">
                        <div className="left-blance">
                          <span>
                            <img
                              src="/img/header/right-icon/wallet.svg"
                              alt="icon"
                            />
                          </span>
                          <span className="text-blabce">Balance</span>
                        </div>
                        <span className="blance">$300</span>
                      </div>
                      <div className="betslip-wrapper">
                        <Link href="#0" className="left-betslip">
                          <span>
                            <img
                              src="/img/header/right-icon/bed.svg"
                              alt="icon"
                            />
                          </span>
                          <span className="text-bets">Bet Slip</span>
                        </Link>
                        <Link href="#0" className="left-betslip">
                          <span>
                            <img
                              src="/img/header/right-icon/bets.svg"
                              alt="icon"
                            />
                          </span>
                          <span className="text-bets">My Bets</span>
                        </Link>
                      </div>
                      <div className="combo-box">
                        <ul className="nav">
                          <li className="nav-item">
                            <Link
                              className="nav-link link-secondary"
                              data-bs-toggle="tab"
                              data-bs-target="#coombomobile"
                              href="#"
                            >
                              <span>pari unique</span>
                            </Link>
                          </li>
                          <li className="nav-item">
                            <Link
                              className="nav-link link-secondary active"
                              data-bs-toggle="tab"
                              data-bs-target="#bbetsmobile"
                              href="#"
                            >
                              <span>Combiné</span>
                            </Link>
                          </li>
                        </ul>
                        <div className="tab-content" id="tabContentboxesmobile">
                          <div
                            className="tab-pane fade"
                            id="coombomobile"
                            role="tabpanel"
                          >
                            <div className="combo-wrapper">
                              <div className="combo-wrapper">
                                <div className="close-box">
                                  <div className="close-items">
                                    <div className="close-head">
                                      <span>Latvia vs Moldova</span>
                                      <span className="close">
                                        <i className="fas fa-xmark"></i>
                                      </span>
                                    </div>
                                    <div className="match-fixing">
                                      <div className="match-items">
                                        <div className="match-items-left">
                                          <div className="icon">
                                            <img
                                              src="/img/header/right-icon/footaball.svg"
                                              alt="icon"
                                            />
                                          </div>
                                          <div className="cont">
                                            <span>Moldova</span>
                                            <span className="winner">
                                              Match Winner
                                            </span>
                                          </div>
                                        </div>
                                        <div className="match-items-right">
                                          <div className="icon">
                                            <img
                                              src="/img/header/right-icon/uptodwon.svg"
                                              alt="icon"
                                            />
                                          </div>
                                          <span>5.20</span>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                                <div className="combo-switch">
                                  <span>
                                    Accepter tous les changements de cotes
                                  </span>
                                  <label className="switch-com">
                                    <input
                                      type="checkbox"
                                      className="checkbox"
                                      hidden
                                    />
                                    <span className="checkbox-label">
                                      <span className="ball"></span>
                                    </span>
                                  </label>
                                </div>
                                <div className="ammount-items">
                                  <form action="#">
                                    <input
                                      type="number"
                                      placeholder="Bet Amount"
                                    />
                                    <button type="submit">Max</button>
                                  </form>
                                </div>
                                <div className="possible-win">
                                  <span>Possible win</span>
                                  <span className="amount">$300</span>
                                </div>
                                <div className="combo-footer">
                                  <Link href="#0" className="cmn--btn">
                                    <span> Placer un pari</span>
                                  </Link>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div
                            className="tab-pane fade show active"
                            id="bbetsmobile"
                            role="tabpanel"
                          >
                            <div className="combo-wrapper">
                              <div className="close-box">
                                <div className="close-items">
                                  <div className="close-head">
                                    <span>Scotland vs Ukraine</span>
                                    <span className="close">
                                      <i className="fas fa-xmark"></i>
                                    </span>
                                  </div>
                                  <div className="match-fixing">
                                    <div className="match-items">
                                      <div className="match-items-left">
                                        <div className="icon">
                                          <img
                                            src="/img/header/right-icon/footaball.svg"
                                            alt="icon"
                                          />
                                        </div>
                                        <div className="cont">
                                          <span>Scotland</span>
                                          <span className="winner">
                                            Match Winner
                                          </span>
                                        </div>
                                      </div>
                                      <div className="match-items-right">
                                        <div className="icon">
                                          <img
                                            src="/img/header/right-icon/uptodwon.svg"
                                            alt="icon"
                                          />
                                        </div>
                                        <span>3.20</span>
                                      </div>
                                    </div>
                                    <div className="match-items">
                                      <div className="match-items-left">
                                        <div className="icon">
                                          <img
                                            src="/img/header/right-icon/footaball.svg"
                                            alt="icon"
                                          />
                                        </div>
                                        <div className="cont">
                                          <span>Draw</span>
                                          <span className="winner">
                                            Match Winner
                                          </span>
                                        </div>
                                      </div>
                                      <div className="match-items-right">
                                        <div className="icon">
                                          <img
                                            src="/img/header/right-icon/uptodwon.svg"
                                            alt="icon"
                                          />
                                        </div>
                                        <span>4.60</span>
                                      </div>
                                    </div>
                                    <p>
                                      Add 2 more outcome(s) with odds greater
                                      than 1.4 to get x1.08
                                    </p>
                                    <div className="match-items match-progress">
                                      <div className="match-items-left">
                                        <div className="prabox-wrap">
                                          <div className="terminal-bar">
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                            <span></span>
                                          </div>
                                          <div className="bar-count">
                                            <p>x1.08</p>
                                            <p>x1,15</p>
                                            <p>x1.20</p>
                                            <p>x1.50</p>
                                          </div>
                                        </div>
                                      </div>
                                      <div className="match-items-right">
                                        <div className="icon">
                                          <img
                                            src="/img/header/right-icon/uptodwon.svg"
                                            alt="icon"
                                          />
                                        </div>
                                        <span>1.00</span>
                                      </div>
                                    </div>
                                    <div className="match-items match-odds">
                                      <div className="match-items-left">
                                        <div className="cont">
                                          <span>Total des cotes</span>
                                        </div>
                                      </div>
                                      <div className="match-items-right">
                                        <div className="icon">
                                          <img
                                            src="/img/header/right-icon/uptodwon.svg"
                                            alt="icon"
                                          />
                                        </div>
                                        <span>12.19</span>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </div>
                              <div className="combo-switch">
                                <span>Accept all odds changes</span>
                                <label className="switch-com">
                                  <input
                                    type="checkbox"
                                    className="checkbox"
                                    hidden
                                  />
                                  <span className="checkbox-label">
                                    <span className="ball"></span>
                                  </span>
                                </label>
                              </div>
                              <div className="ammount-items">
                                <form action="#">
                                  <input
                                    type="number"
                                    placeholder="Bet Amount"
                                  />
                                  <button type="submit">Max</button>
                                </form>
                              </div>
                              <div className="possible-win">
                                <span>Possible win</span>
                                <span className="amount">$300</span>
                              </div>
                              <div className="combo-footer">
                                <Link href="#0" className="cmn--btn">
                                  <span> Placer un pari</span>
                                </Link>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="accordion-box">
                        <div className="accordion" id="accordionExamplemy">
                          <div className="accordion-item">
                            <div
                              className="accordion-header"
                              id="headingThree03"
                            >
                              <button
                                className="accordion-button collapsed"
                                type="button"
                                data-bs-toggle="collapse"
                                data-bs-target="#collapseThree"
                                aria-expanded="false"
                                aria-controls="collapseThree"
                              >
                                <span className="icon">
                                  <i className="fa-sharp fa-solid fa-gear"></i>
                                </span>
                                <span>Paramettre</span>
                              </button>
                              <div
                                id="collapseThreethree"
                                className="accordion-collapse collapse"
                                data-bs-parent="#accordionExample"
                              >
                                <div className="accordion-body">
                                  <Link href="#0" className="condition-box">
                                    Terms & Conditions
                                  </Link>
                                  <div className="select-wrap">
                                    <div className="select-one">
                                      <Select
                                        instanceId={useId()}
                                        defaultValue={selectedLangOption}
                                        onChange={setSelectedLangOption}
                                        options={langOptions}
                                        components={{
                                          IndicatorSeparator: () => null,
                                        }}
                                        styles={customStyles}
                                      />
                                    </div>
                                    <div className="select-two">
                                      <Select
                                        instanceId={useId()}
                                        defaultValue={selectedDacimalOption}
                                        onChange={setSelectedDacimalOption}
                                        options={decimalOptions}
                                        components={{
                                          IndicatorSeparator: () => null,
                                        }}
                                        styles={customStyles}
                                      />
                                    </div>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="popular-bets">
                      <div className="head">
                        <h6>Popular bets</h6>
                      </div>
                      <ul className="popoular-body">
                        <li className="popular-items">
                          <label className="popular-itmes-left">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              id="flexCheckDefault4"
                            />
                            <span className="icon">
                              <i className="icon-football"></i>
                            </span>
                            <span className="cont">
                              <span className="text1">1x2</span>
                              <span className="text2">Prance</span>
                              <span className="text3">France - Austria</span>
                            </span>
                          </label>
                          <div className="popular-itmes-right">
                            <span>2.37</span>
                          </div>
                        </li>
                        <li className="popular-items">
                          <label className="popular-itmes-left">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              id="flexCheckDefault5"
                            />
                            <span className="icon">
                              <i className="icon-football"></i>
                            </span>
                            <span className="cont">
                              <span className="text1">1x2</span>
                              <span className="text2">Turkey</span>
                              <span className="text3">Turkey - Luxembourg</span>
                            </span>
                          </label>
                          <div className="popular-itmes-right">
                            <span>1.37</span>
                          </div>
                        </li>
                        <li className="popular-items">
                          <label className="popular-itmes-left">
                            <input
                              className="form-check-input"
                              type="checkbox"
                              id="flexCheckDefault6"
                            />
                            <span className="icon">
                              <i className="icon-football"></i>
                            </span>
                            <span className="cont">
                              <span className="text1">1x2</span>
                              <span className="text2">Alkmaar</span>
                              <span className="text3">Alkmaar - Apollon</span>
                            </span>
                          </label>
                          <div className="popular-itmes-right">
                            <span>3.47</span>
                          </div>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
